services:
  web:
    build: .
    image: python:3.13
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env

    working_dir: /data/compose/4/
    command: python app.py  