services:
  web:
    image: python:3.13
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env  
    working_dir: /background
    command: python app.py
