services:
  web:
    build: .
    image: python:3.13
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - /volume1/Docker/ed_colonisation
    working_dir: /volume1/Docker/ed_colonisation
    command: sh -c "pip install -r requirements.txt && python app.py"