services:
  web:
    image: python:3.13
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
      
    RUN pip install --no-cache-dir -r requirements.txt
    command: python app.py
